### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Jelle-S** [digipolisgent/drupal-copy-profile#1]
As requested by @daften.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L3
File docblock can be skipped in PSR-4 namespaced classes.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L14
Why use ... as ... ? There's no name collision?

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php
Entire file:
Docblock:
  - add description to class properties.
  - add description to method parameters.
  - add description to return documentation.
  - Use fully qualified classnames for typehinting (e.g. \Composer\Package\PackageInterface instead of PackageInterface.
  - Use string[] instead of array[string] for typehinting an array of items.
  - Max comment length = 80.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L44
Personal preference: Add \Composer\Script\Event as a use statement.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L68
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L89
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L104
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L143
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L171
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php#L2
File docblock can be skipped in PSR-4 namespaced classes.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php
Entire file:
Docblock:
  - add description to class properties.
  - add description to method parameters.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php#L51
Personal preference: Add \Composer\Script\Event as a use statement.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php#L60
Personal preference: Add \Composer\Script\Event as a use statement.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L3
File docblock can be skipped in PSR-4 namespaced classes.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php
Entire file:
Docblock:
  - add description to class properties.
  - add description to return documentation.
  - Max comment length = 80.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L101
Punctuation.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L127
s/composer.json/profile.profile/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L129
No need to redeclare $contents.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L130
s/composer.json/profile.install/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L130
s/composer.json/profile.info.yml/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L211
s/param $command/param string $command/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L231
Why not $this->fs->mkdir()?

**Comment by daften** [comment]
@Jelle-S @this->fs->mkdir() doesn't exist. Closest to it is $this->fs->ensureDirectoryExists(), which has a bit of overhead.
